#!/bin/bash
set -e
#SUBS="BbArchitecture BbReferenceModel"
SUBS="Standard"
#SUBS="WhoDhiClient WhoDhiHealthSystemManager WhoDhiDataService WhoDhiSystemCategory WhoDhiHealthcareProvider"

#TEMPLATES="subfeature feature function applicationsystem featurecitation functioncitation"
TEMPLATES="standard"
rm -f /tmp/combined.nt
for s in $SUBS
do
 if [ ! -d "${s}" ]
 then
  echo "** ERROR: DIRECTORY ${s} DOES NOT EXIST, SKIPPING ${s} ********************************"
 else
  echo "** DIRECTORY ${s} ******************************************************************************"
  mkdir -p ${s}/tmp
  mkdir -p ${s}/tmp/old
  mv ${s}/tmp/*.nt ${s}/tmp/old || true
  for t in $TEMPLATES
  do
   csv="${s}/${t}.csv"
   if [ -e $csv ]
   then
    echo "**** Using Template ${t} on ${csv} **************************************************************************"
    mkdir -p ${s}/out
    sed "s|{SUB}|${s}|g" ${t}.tarql.template > ${s}/tmp/${t}.tarql
    tarql ${s}/tmp/${t}.tarql | rapper -i turtle - http://hitontology.eu/ontology/ > ${s}/tmp/${t}.nt
   else
    echo "**** WARNING: ${csv} DOES NOT EXIST, SKIPPING TEMPLATE ${t} *******************************"
   fi
  done 
  echo "** Merging ***********************************x************"
  rapper -i turtle ${s}/base.ttl > ${s}/tmp/base.nt 
  cat prefix.ttl ${s}/tmp/*.nt | rapper -i turtle -o turtle - http://hitontology.eu/ontology/ > ${s}/out/all.ttl
  rapper -i turtle -o ntriples ${s}/out/all.ttl >> /tmp/combined.nt
  echo "** Testing ************************************************"
  rapper -i turtle -c ${s}/out/all.ttl
  echo "********************************************************************************************************"
 fi
done
echo "********************* test combination ******************"
sort /tmp/combined.nt -o /tmp/combined.nt
rapper -i turtle -c /tmp/combined.nt
cat prefix.ttl /tmp/combined.nt | rapper -i turtle -o turtle - http://hitontology.eu/ontology/ > /tmp/combined.ttl
echo "/tmp/combined.ttl"
