#!/bin/bash
set -e
SUBS="WhoDhiClient WhoDhiHealthcareProvider WhoDhiHealthSystemManager WhoDhiDataService"
TEMPLATES="subfeature feature function"
for s in $SUBS
do
 if [ ! -d "${s}" ]
 then
  echo "** ERROR: DIRECTORY ${s} DOES NOT EXIST, SKIPPING ${s} ********************************"
 else
  echo "** DIRECTORY ${s} ******************************************************************************"
  for t in $TEMPLATES
  do
   csv="${s}/${t}.csv"
   if [ -e $csv ]
   then
    echo "**** Using Template ${t} on ${csv} **************************************************************************"
    mkdir -p ${s}/tmp
    mkdir -p ${s}/out
    sed "s|{SUB}|${s}|g" ${t}.tarql.template > ${s}/tmp/${t}.tarql
    tarql ${s}/tmp/${t}.tarql | rapper -i turtle - http://hitontology.eu/ontology/ > ${s}/tmp/${t}.nt
   else
    echo "**** WARNING: ${csv} DOES NOT EXIST, SKIPPING TEMPLATE ${t} *******************************"
   fi
  done 
  echo "** Merging ***********************************x************"
  rapper -i turtle ${s}/base.ttl > ${s}/tmp/base.nt 
  cat prefix.ttl ${s}/tmp/*.nt | rapper -i turtle -o turtle - http://hitontology.eu/ontology/ > ${s}/out/all.ttl
  echo "** Testing ************************************************"
  rapper -i turtle -c ${s}/out/all.ttl
  echo "********************************************************************************************************"
 fi
done
